### PR TITLE
Optimize all PNG files.

### PR DESCRIPTION
**Pull request by manthey**
Optimize all png files without changing how they look.

### CODE REVIEW

**Comment by jeffbaumes** [comment]
I am convinced that these images do indeed look the same. LGTM.

**Comment by zachmullen** [comment]
Neat, is this just using more aggressive deflate parameters, or were they just not compressed at all before...?

**Comment by manthey** [comment]
It varied.  I ran `optipng` with the defaults on all pngs in the repo.  Some compressed a few bytes (possibly removing the comment of what app made the png).  Others compressed hugely.

**Comment by jeffbaumes** [comment]
@zachmullen you seem shocked that I would overlook this :smile: Indeed, I never performed compression.

**Pull request merged**
