### PR TITLE
Update logos

### PR DESCRIPTION
**Pull request by waxlamp**
This adds Girder Worker and Candela logos, and updates some of the others.

### CODE REVIEW

**Comment by waxlamp** [comment]
This is marked WIP while I wait for some final versions of existing logos from Steve. Once those are updated within the site, I'll remove the WIP tag.

**Comment by waxlamp** [comment]
I've got all the logos from Steve, but it turns out the ones I was waiting on weren't being used in the site with circular mattes.

This is ready for review now.

**Review by jeffbaumes — APPROVED** [review]
Nice, thanks. So it looks like there is an "official" logo location on data.kitware.com now? Would you mind communicating this to the data-analytics list?

**Comment by waxlamp** [comment]
I just figured it would be good to have a single place where all logos (or, eventually, other assets) are stored. I'll send a message to data-analytics about it.

**Pull request merged**
