### PR TITLE
New background image

### PR DESCRIPTION
**Pull request by jeffbaumes**
screen shot 2015-10-03 at 12 41 37 pm

### CODE REVIEW

**Comment by cpatrick** [comment]
:+1:

**Comment by wschroed** [comment]
+1

**Comment by sobieavila** [comment]
I do like it better than the previous background image  - but note that when I see the first page I actually see the first two (and a piece of the third). So part of what I don't like about the current design in how that first page looks so different from the other pages (the only one with a background) and how it breaks the "dark" then "light" pattern of the scrolling site (because I'd say the background appears to be white so it seems like part of the next page.)  My thought would be to have Steve design you something self contained (and with a transparent background) that could be put on the grey background, and then you just have the alternating "dark" then "light" backgrounds (I tend to look at Apple's pages for examples of well done long scrolling "product" pages - for example http://www.apple.com/ipad-mini-4/ and http://www.apple.com/apple-pencil/) Of course, I think it would be best if you could get some image / images / graphic up there on the first page that somehow conveys what "Resonant" is (I know, that it tough - but still, it would be great). 

resonantfirstpage2

**Comment by jeffbaumes** [comment]
Thanks for the input @sobieavila. I'll merge this for now as an improvement over what we had. One solution is to start the pattern by starting with light, then make capabilities dark, then light, etc. The current graphic has a white background and it would be nontrivial for me to get it to exactly match the dark color, though I'm sure Steve could do it quickly.

**Pull request merged**
