### PR TITLE
Adding permit use case

### PR DESCRIPTION
**Pull request by jeffbaumes**
From XDATA hackathon this week.

### CODE REVIEW

**Comment by cpatrick** [comment]
Sweet!

**Comment by cpatrick** [comment]
One thing I will say is that it took some fiddling for me to get the demo into a usable state...

**Comment by jeffbaumes** [comment]
Yes we need to fix up several things - like starting in NYC instead of Boston. Could you post your struggles on https://github.com/XDATA-Year-3/geoapp issues so @manthey can see them?

**Comment by manthey** [comment]
Next week, we can fix up the various issues with the demo (start location,
some animation weirdness, legends for the data, default to loading data,
some text issues).

On Fri, Jan 15, 2016 at 1:17 PM, Jeffrey Baumes notifications@github.com
wrote:

> Yes we need to fix up several things - like starting in NYC instead of
> Boston. Could you post your struggles on
> https://github.com/XDATA-Year-3/geoapp issues so @manthey
> https://github.com/manthey can see them?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Kitware/resonant-website/pull/27#issuecomment-172041296
> .

## 

David Manthey
R&D Engineer
Kitware Inc.
(518) 881-4439

**Comment by zachmullen** [comment]
I just checked out this demo, and it's cool. What are "permits" and what are "violations" in this context?

**Comment by cpatrick** [comment]
@manthey just touched on my issues :smile:

**Comment by manthey** [comment]
I've updated the demo at demo.kitware.com/bostonpermits .  See I think I've addressed all of the listed issues in https://github.com/XDATA-Year-3/geoapp/pull/220 .  The demo could still use updated help and probably other things -- please let me know of file issues at https://github.com/XDATA-Year-3/geoapp

**Comment by jeffbaumes** [comment]
The updated demo looks great! I think we're ready to merge this use case, which I'll do if someone can confirm with LGTM.

**Comment by jeffbaumes** [comment]
No LGTM :( but I'm going to go ahead and merge since I believe we addressed major issues. We will continue to refine the demo.

**Pull request merged**
